@startuml

participant  "Web Server"          as web_server
participant  "Falcon App"          as falcon
participant  "Logging middleware"  as logging_middleware
participant  "Falcon Resource"     as resource

web_server -> falcon         : запрашивает приложение
falcon -> logging_middleware : вызывает process_request
falcon -> falcon             : находит нужный resource
falcon -> logging_middleware : вызывает process_resource
falcon -> resource           : вызывает найденный ресурс
falcon -> logging_middleware : вызывает process_response
web_server <- falcon : приложение возвращает\nответ серверу

@enduml
