"""create authors table

Revision ID: 1918d268651b
Revises: fa6d7fd96a03
Create Date: 2022-02-09 09:01:50.631954

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1918d268651b'
down_revision = 'fa6d7fd96a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'blog_authors',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['blog_users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_authors')
    # ### end Alembic commands ###
