"""create posts-tags association table

Revision ID: 1f08341c8034
Revises: 6716d19ca670
Create Date: 2022-02-11 08:20:47.783614

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1f08341c8034'
down_revision = '6716d19ca670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'posts_tags_association',
        sa.Column('post_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], ),
        sa.ForeignKeyConstraint(['tag_id'], ['blog_tags.id'], ),
        sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts_tags_association')
    # ### end Alembic commands ###
