"""create posts-tags association table

Revision ID: 441cf7b00555
Revises: 4d346de430e3
Create Date: 2022-02-10 08:22:01.477880

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '441cf7b00555'
down_revision = '4d346de430e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'posts_tags_association',
        sa.Column('post_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], ),
        sa.ForeignKeyConstraint(['tag_id'], ['blog_tags.id'], ),
        sa.PrimaryKeyConstraint('post_id', 'tag_id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts_tags_association')
    # ### end Alembic commands ###
