"""create tags table

Revision ID: 6716d19ca670
Revises: 6c00778ecefc
Create Date: 2022-02-11 08:11:28.767970

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6716d19ca670'
down_revision = '6c00778ecefc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'blog_tags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_tags')
    # ### end Alembic commands ###
