@startuml
start
:Прийти на кухню;
if (Чайник пустой?) then (Да (пустой))
    :Налить воды в чайник;
else (Нет)
endif
:Вскипятить чайник;

if (Есть ли чистая кружка?) then (Да)
    :Взять чистую кружку;
else (Нет)
    :Помыть грязную кружку;
endif

:Положить заварку / пакетик в кружку;
:Залить горячей водой;

end
@enduml
