@startuml
start
:Прийти на кухню;

if (Чайник пустой?) then (Да)
    :Налить воды в чайник;
else (Нет)
endif

:Вскипятить чайник;

if (Есть чистая кружка?) then (Да)
    :Взять чистую кружку;
else (Нет)
    :Помыть грязную кружку;
endif

:Положить заварку в кружку;
:Залить горячей водой;
'stop
end
@enduml
